CREATE TABLE IF NOT EXISTS home_articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image TEXT NOT NULL,
    description VARCHAR(255) NOT NULL,
    place VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    text TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;